# Generated by Django 5.1.2 on 2024-10-31 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_axle_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Engine_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Fault_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Recovery_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Service_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Steerable_axle_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Technical_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial_number', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('transmission_serial_number', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_serial_number', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('steerable_axle_serial_number', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('supply_contract_number', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('configuration', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('service_company', models.CharField(max_length=255, verbose_name='Сервисная компания')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.drive_axle_handbook', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main.engine_handbook', verbose_name='Модель двигателя')),
                ('steerable_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.steerable_axle_handbook', verbose_name='Модель управляемого моста')),
                ('equipment_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main.technical_handbook', verbose_name='Модель техники')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.transmission_handbook', verbose_name='Модель трансмиссии')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('hours', models.FloatField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=255, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='Main.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.maintenance_handbook', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.service_company', verbose_name='Сервисная компания')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.FloatField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('used_spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.FloatField(editable=False, verbose_name='Время простоя техники')),
                ('failure_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.fault_handbook', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='Main.machine', verbose_name='Машина')),
                ('recovery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.recovery_handbook', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.service_company', verbose_name='Сервисная компания')),
            ],
        ),
    ]
