# Generated by Django 5.1.4 on 2025-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_api_keys_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys',
            name='name',
            field=models.TextField(default='Новый ключ', verbose_name='Название'),
        ),
    ]
