# Generated by Django 5.1.4 on 2025-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_api_keys_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость ключа'),
        ),
    ]
