# Generated by Django 5.1.4 on 2025-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_api_keys_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_keys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='api_keys',
            name='key',
            field=models.TextField(verbose_name='Ключ'),
        ),
    ]
