# Generated by Django 5.1.4 on 2025-01-07 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_api_keys_id_alter_api_keys_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api_keys',
            new_name='ApiKey',
        ),
    ]
