# Generated by Django 5.1.4 on 2025-01-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_rename_api_keys_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.service_company', verbose_name='Сервисная компания'),
        ),
    ]
