# Generated by Django 5.1.4 on 2025-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_drive_axle_handbook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='downtime',
            field=models.FloatField(verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
